### ISSUE TITLE
Lizenz und eigene Verwendung

### ISSUE THREAD

**Issue by mathiassiegmund** [naltatis/openligadb-json-api#1]
Hi, erstmal Danke für die Umsetzung um von der unsäglichen SOAP-Schnittstelle wegzukommen.

Meine Frage ist jetzt, unter welche Lizenz das Projekt steht bzw. wie ich es selber einsetzen darf?

Gruß
Mathias

**Comment by mathiassiegmund** [comment]
Und was hat das mit dem Thema zu tun?

**Comment by naltatis** [comment]
Habe gerade die Lizenz in der Readme ergänzt.

Kurz:
Du kannst damit machen was du möchtest.
