### ISSUE TITLE
Leere Antwortmengen

### ISSUE THREAD

**Issue by johorst** [naltatis/openligadb-json-api#2]
Das ist doch hier die issue list http://openligadb-json.heroku.com?
Ich würde die darauf laufende json api gerne benutzen.
Allerdings suche ich noch ein wenig nach Orientierung ... 
(Die ersten Testballons waren nicht sehr erfolgreich.)
Ein Ansatz war: per jQuery Aufruf getJSON (http://api.jquery.com/jQuery.getJSON/), der in jsfiddle leere Antworten erzeugt.
http://jsfiddle.net/6gPVQ/4/ - firebug ezigt mir den richtig zusammengebauten GET-Aufruf. Keine Antwort. Kopiere ich den richtig zusammengebauten GET-Aufruf raus und starte ihn im Browser, kommt die Ergebnismenge.

Mögliche Antwort: zur Verhinderung von Cross Site Scripting Attacken ist es nicht möglich, jsfiddle.net damit zu beauftragen, die Ergebnismenge von http://openligadb-json.heroku.com anzuzeigen.
Das hätte ich gerne bestätigt oder falsifiziert.
Vielen Dank vorab.

**Comment by naltatis** [comment]
Ja, hier schlägt die CrossDomainPolicy im Browser an. Es ist generell erstmal nicht möglich Ajax-Requests von einer Domain auf die andere zu machen. Es gibt Umwege, wie bspw. über JSONP. Das setzt aber Server-Unterstützung voraus.

**Comment by johorst** [comment]
Vielen Dank.
