### ISSUE TITLE
"last_match_by_league_team" always returning empty data

### ISSUE THREAD

**Issue by kplanz** [naltatis/openligadb-json-api#4]
Hey,
I'm getting `"No Data Available"` messages when calling `last_match_by_league_team`. Using openligadb webservice works fine. 
I think it's because `last_match_by_league_team` should be included in this line as well: https://github.com/naltatis/openligadb-json-api/blob/master/lib/openligadb.rb#L30 (`leagueId` vs. `leagueID`)

Should be an easy one ;)

Karsten

**Comment by naltatis** [comment]
Should work fine now ...
http://openligadb-json.heroku.com/api/last_match_by_league_team?team_id=100&league_id=159

Thanks for reporting!
naltatis
