### ISSUE TITLE
Start own complete API documentation

### ISSUE THREAD

**Issue by minthemiddle** [naltatis/openligadb-json-api#7]
Let's face it. OpenLiga's documentation is horrible. I tried to find out how to query the current Bundesliga table but could not find it amidst the XML chaos.

It would be splendid to start an own complete API documentation, f.e. in Github's wiki.

**Comment by naltatis** [comment]
Totally agreed. Do you start one?

**Comment by geraldb** [comment]
FYI: You're invited to check out (or use) the [football.db](https://github.com/openfootball) as an alternative. Current [API docs for JSON (in development)](https://github.com/openfootball/api) here. Cheers.  PS: Great project - keep it up.

**Comment by naltatis** [comment]
Nice!
